version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.12
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Keep cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - 'node_modules'

      # Test
      - run:
          name: Tests
          command: npm test

      # Coverage
      - run:
          name: Coverage
          command: npm run coverage
